/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface DataExports {
  completed_at: Date | null;
  error_message: string | null;
  expires_at: Date | null;
  file_size: number | null;
  id: string;
  requested_at: Generated<Date | null>;
  s3_key: string | null;
  status: Generated<"completed" | "failed" | "pending" | "processing">;
  user_id: string;
}

export interface Follows {
  created_at: Date;
  follower_id: string;
  following_id: string;
  id: string;
  updated_at: Date;
}

export interface Hashtags {
  created_at: Date | null;
  hashtag: string;
  id: string;
  updated_at: Date | null;
}

export interface KnexMigrations {
  batch: number | null;
  id: Generated<number>;
  migration_time: Date | null;
  name: string | null;
}

export interface KnexMigrationsLock {
  index: Generated<number>;
  is_locked: number | null;
}

export interface Links {
  code: string;
  count: Generated<number>;
  created_at: Date | null;
  id: string;
  link: string;
  updated_at: Date | null;
}

export interface Notifications {
  count: Generated<number>;
  created_at: Date | null;
  id: string;
  is_read: Generated<number>;
  post_id: string | null;
  reply_id: string | null;
  type: "Follow" | "Like" | "Mention" | "Reply" | "Reshare";
  updated_at: Date | null;
  user_id: string;
}

export interface NotificationsTriggers {
  created_at: Date | null;
  id: string;
  notification_id: string;
  trigger_user_id: string;
  updated_at: Date | null;
}

export interface PostHashtags {
  created_at: Date | null;
  hashtag: string;
  hashtag_id: string;
  id: string;
  post_id: string;
  updated_at: Date | null;
}

export interface PostLikes {
  created_at: Date | null;
  id: string;
  post_id: string;
  updated_at: Date | null;
  user_id: string;
}

export interface PostLinks {
  created_at: Date | null;
  id: string;
  link_id: string;
  post_id: string;
  updated_at: Date | null;
}

export interface PostMentions {
  created_at: Date | null;
  id: string;
  post_id: string;
  updated_at: Date | null;
  user_id: string | null;
  username: string;
}

export interface Posts {
  content: string;
  created_at: Date | null;
  external_id: string | null;
  id: string;
  lexical: string;
  location: Generated<string>;
  parent_id: string | null;
  reshare_id: string | null;
  stats_likes: Generated<number>;
  stats_replies: Generated<number>;
  stats_shares: Generated<number>;
  stats_views: Generated<number>;
  updated_at: Date | null;
  user_id: string;
}

export interface RssSources {
  bio: string | null;
  bot_user_id: string | null;
  category: string | null;
  created_at: Generated<Date>;
  id: string;
  language: Generated<string>;
  name: string;
  submitted_by: string;
  update_frequency: Generated<string>;
  updated_at: Generated<Date>;
  url: string;
}

export interface RssSuggestions {
  admin_notes: string | null;
  created_at: Generated<Date>;
  id: string;
  is_owner: Generated<number>;
  language: Generated<string>;
  rejection_reason: string | null;
  status: Generated<"accepted" | "pending" | "rejected">;
  submitted_by: string;
  updated_at: Generated<Date>;
  url: string;
}

export interface Users {
  bio: string | null;
  bot_type: "rss" | "system" | null;
  created_at: Date | null;
  custom_domain: string | null;
  deleted_at: Date | null;
  domain_verification_status: "failed" | "pending" | "verified" | null;
  domain_verification_token: string | null;
  domain_verified_at: Date | null;
  email: string;
  email_verification_token: string | null;
  email_verification_token_expires_at: Date | null;
  id: string;
  is_admin: Generated<number>;
  link: string | null;
  name: string;
  notif_email_freq: Generated<"daily" | "hourly" | "off" | "weekly">;
  notif_email_last_sent_at: Date | null;
  password: string;
  password_reset_token: string | null;
  password_reset_token_expires_at: Date | null;
  updated_at: Date | null;
  username: string;
}

export interface DB {
  data_exports: DataExports;
  follows: Follows;
  hashtags: Hashtags;
  knex_migrations: KnexMigrations;
  knex_migrations_lock: KnexMigrationsLock;
  links: Links;
  notifications: Notifications;
  notifications_triggers: NotificationsTriggers;
  post_hashtags: PostHashtags;
  post_likes: PostLikes;
  post_links: PostLinks;
  post_mentions: PostMentions;
  posts: Posts;
  rss_sources: RssSources;
  rss_suggestions: RssSuggestions;
  users: Users;
}
