/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Hashtags {
  created_at: Date | null;
  hashtag: string;
  id: string;
  updated_at: Date | null;
}

export interface KnexMigrations {
  batch: number | null;
  id: Generated<number>;
  migration_time: Date | null;
  name: string | null;
}

export interface KnexMigrationsLock {
  index: Generated<number>;
  is_locked: number | null;
}

export interface Links {
  code: string;
  count: Generated<number>;
  created_at: Date | null;
  id: string;
  link: string;
  updated_at: Date | null;
}

export interface PostHashtags {
  created_at: Date | null;
  hashtag: string;
  hashtag_id: string;
  id: string;
  post_id: string;
  updated_at: Date | null;
}

export interface PostLinks {
  created_at: Date | null;
  id: string;
  link_id: string;
  post_id: string;
  updated_at: Date | null;
}

export interface PostMentions {
  created_at: Date | null;
  id: string;
  post_id: string;
  updated_at: Date | null;
  user_id: string | null;
  username: string;
}

export interface Posts {
  content: string;
  created_at: Date | null;
  external_id: string | null;
  id: string;
  lexical: string;
  location: Generated<string>;
  parent_id: string | null;
  reshare_id: string | null;
  stats_likes: Generated<number>;
  stats_replies: Generated<number>;
  stats_shares: Generated<number>;
  stats_views: Generated<number>;
  updated_at: Date | null;
  user_id: string;
}

export interface Users {
  bio: string | null;
  bot_type: "rss" | "system" | null;
  created_at: Date | null;
  custom_domain: string | null;
  deleted_at: Date | null;
  domain_verification_status: "failed" | "pending" | "verified" | null;
  domain_verification_token: string | null;
  domain_verified_at: Date | null;
  email: string;
  id: string;
  name: string;
  password: string;
  updated_at: Date | null;
  username: string;
}

export interface DB {
  hashtags: Hashtags;
  knex_migrations: KnexMigrations;
  knex_migrations_lock: KnexMigrationsLock;
  links: Links;
  post_hashtags: PostHashtags;
  post_links: PostLinks;
  post_mentions: PostMentions;
  posts: Posts;
  users: Users;
}
