/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface KnexMigrations {
  batch: number | null;
  id: Generated<number>;
  migration_time: Date | null;
  name: string | null;
}

export interface KnexMigrationsLock {
  index: Generated<number>;
  is_locked: number | null;
}

export interface Posts {
  content: string;
  created_at: Date | null;
  id: string;
  lexical: string;
  location: Generated<string>;
  parent_id: string | null;
  reshare_id: string | null;
  stats_likes: Generated<number>;
  stats_replies: Generated<number>;
  stats_shares: Generated<number>;
  stats_views: Generated<number>;
  updated_at: Date | null;
  user_id: string;
}

export interface Users {
  bio: string | null;
  created_at: Date | null;
  deleted_at: Date | null;
  email: string;
  id: string;
  name: string;
  password: string;
  updated_at: Date | null;
  username: string;
}

export interface DB {
  knex_migrations: KnexMigrations;
  knex_migrations_lock: KnexMigrationsLock;
  posts: Posts;
  users: Users;
}
